name: Weekly Gathering Tasks

on:
  schedule:
    - cron: '7 0 * * 1'   # 월요일 KST 09:07
    - cron: '33 3 * * 0'  # 일요일 KST 12:33
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 discord.py

      - name: Run
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          QT_CHANNEL_ID: ${{ secrets.QT_CHANNEL_ID }}
          SUNDAY_CHANNEL_ID: ${{ secrets.SUNDAY_CHANNEL_ID }}
        run: python main.py --mode task